# Site settings
title: Casey Watts!
description: > # this means to ignore newlines until "baseurl:"
  Casey Watts! likes system optimizing, technology, singing, dancing, blowing bubbles, enthusiasm, clear communication, hugs.
  He loves helping people collaborate together more effectively (people systems~).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://caseywatts.com" # the base hostname & protocol for your site
enforce_ssl: "caseywatts.com" # the base hostname & protocol for your site
twitter_username: kyloma
github_username:  caseywatts

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js]
