# Site settings
title: Casey Watts Blog
description: > # this means to ignore newlines until "baseurl:"
  Casey Watts likes to optimize systems.
  He likes technology, singing, dancing, and blowing bubbles.
  He loves helping people collaborate together more effectively.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://caseywatts.github.io" # the base hostname & protocol for your site
twitter_username: kyloma
github_username:  caseywatts

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js]
