# Site settings
title: Casey Watts
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Casey Watts!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://caseywatts.github.io" # the base hostname & protocol for your site
twitter_username: kyloma
github_username:  caseywatts

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js]
